### PR TITLE
RDI-1996 remove sdl2 plugin

### PR DESCRIPTION
**Pull request by aslobodeniuk**
It's moved to git@github.com:fluendo/gst.wasm.git

Issue: RDI_1996

### CODE REVIEW

**Review by cfoch — CHANGES_REQUESTED** [review]
Hey, you forgot to remove the code of sdl2.

**Comment by aslobodeniuk** [comment]
> Hey, you forgot to remove the code of sdl2.

sorry, fixed

**Comment by turran** [comment]
I think this is not really needed. The corresponding `guw` feature should be removed.

**Comment by aslobodeniuk** [comment]
> I think this is not really needed. The corresponding `guw` feature should be removed.

what is guw?

**Pull request closed without merging**
