### PR TITLE
RDI-2056 debugutilsbad

### PR DESCRIPTION
**Pull request by cfoch**

### CODE REVIEW

**Review by aslobodeniuk — APPROVED** [review]

**Comment by turran** [comment]
@cfoch @rgonzalezfluendo Wouldn't be good to group the commits to the corresponding feature as much as possible? I did like this too in the past but then things like the function pointers issues, I added to the feature that does that.

**Comment by cfoch** [comment]
> @cfoch @rgonzalezfluendo Wouldn't be good to group the commits to the corresponding feature as much as possible? I did like this too in the past but then things like the function pointers issues, I added to the feature that does that.

The "[debugutils: fpsdisplaysink: Fix bad pointer to function cast](https://github.com/fluendo/gstreamer/pull/32/commits/9d0bf30b4b5f599b2fe7875a1cefe880ee876a59)" commit must target wasm-main-function-pointer. I agree.

What other feature branch should the rest of commits target?

**Comment by cfoch** [comment]
I splited out the function pointer cast to: https://github.com/fluendo/gstreamer/pull/40

**Comment by cfoch** [comment]
Merged with the following command:

`poetry run guw -l debug gstreamer_gst.wasm.toml update  --keep --backup origin/RDI-2056-debugutilsbad wasm-main-enable`.

Logs:

```
forccon@forccon-fluendo:~/checkout/fluendo/git-upstream-workflow$ poetry run guw -l debug gstreamer_gst.wasm.toml update  --keep --backup origin/RDI-2056-debugutilsbad wasm-main-enable
[2024-11-11 12:02:40,291] INFO main.py:83 Work directory at /tmp/tmpp7bv2_x3
[2024-11-11 12:11:53,683] DEBUG main.py:101 Adding remote freedesktop at git@gitlab.freedesktop.org:gstreamer/gstreamer.git
[2024-11-11 12:11:53,692] DEBUG main.py:103 Fetching remote freedesktop
[2024-11-11 12:15:09,337] INFO main.py:113 Syncing feature meson_fix_nls with previous active wasm-main-base
[2024-11-11 12:15:09,337] DEBUG main.py:118 Creating local branch origin/meson_fix_nls
[2024-11-11 12:15:09,790] DEBUG main.py:63 Rebasing meson_fix_nls onto wasm-main-base until origin/wasm-main-base
[2024-11-11 12:15:09,790] DEBUG main.py:68 Backing up meson_fix_nls into meson_fix_nls-2024-11-11
[2024-11-11 12:15:09,945] INFO main.py:113 Syncing feature wasm-main-function-pointer with previous active meson_fix_nls
[2024-11-11 12:15:09,945] DEBUG main.py:118 Creating local branch origin/wasm-main-function-pointer
[2024-11-11 12:15:10,098] DEBUG main.py:63 Rebasing wasm-main-function-pointer onto meson_fix_nls until origin/meson_fix_nls
[2024-11-11 12:15:10,099] DEBUG main.py:68 Backing up wasm-main-function-pointer into wasm-main-function-pointer-2024-11-11
[2024-11-11 12:15:10,279] INFO main.py:113 Syncing feature wasm-main-enable with previous active wasm-main-function-pointer
[2024-11-11 12:15:10,279] DEBUG main.py:118 Creating local branch origin/wasm-main-enable
[2024-11-11 12:15:10,384] DEBUG main.py:144 Integrating feature wasm-main-enable with origin/RDI-2056-debugutilsbad
[2024-11-11 12:15:10,815] DEBUG main.py:63 Rebasing wasm-main-enable onto wasm-main-function-pointer until origin/wasm-main-function-pointer
[2024-11-11 12:15:10,815] DEBUG main.py:68 Backing up wasm-main-enable into wasm-main-enable-2024-11-11
[2024-11-11 12:15:10,997] INFO main.py:113 Syncing feature wasm-main-test with previous active wasm-main-enable
[2024-11-11 12:15:10,998] DEBUG main.py:118 Creating local branch origin/wasm-main-test
[2024-11-11 12:15:11,138] DEBUG main.py:63 Rebasing wasm-main-test onto wasm-main-enable until origin/wasm-main-enable
[2024-11-11 12:15:11,138] DEBUG main.py:68 Backing up wasm-main-test into wasm-main-test-2024-11-11
[2024-11-11 12:15:11,435] INFO main.py:113 Syncing feature wasm-main-openal with previous active wasm-main-test
[2024-11-11 12:15:11,435] DEBUG main.py:118 Creating local branch origin/wasm-main-openal
[2024-11-11 12:15:11,533] DEBUG main.py:63 Rebasing wasm-main-openal onto wasm-main-test until origin/wasm-main-test
[2024-11-11 12:15:11,533] DEBUG main.py:68 Backing up wasm-main-openal into wasm-main-openal-2024-11-11
[2024-11-11 12:15:11,810] INFO main.py:113 Syncing feature wasm-main-gl-support with previous active wasm-main-openal
[2024-11-11 12:15:11,811] DEBUG main.py:118 Creating local branch origin/wasm-main-gl-support
[2024-11-11 12:15:11,909] DEBUG main.py:63 Rebasing wasm-main-gl-support onto wasm-main-openal until origin/wasm-main-openal
[2024-11-11 12:15:11,910] DEBUG main.py:68 Backing up wasm-main-gl-support into wasm-main-gl-support-2024-11-11
[2024-11-11 12:15:12,227] INFO main.py:113 Syncing feature wasm-main-videodec with previous active wasm-main-gl-support
[2024-11-11 12:15:12,227] DEBUG main.py:118 Creating local branch origin/wasm-main-videodec
[2024-11-11 12:15:12,437] DEBUG main.py:63 Rebasing wasm-main-videodec onto wasm-main-gl-support until origin/wasm-main-gl-support
[2024-11-11 12:15:12,437] DEBUG main.py:68 Backing up wasm-main-videodec into wasm-main-videodec-2024-11-11
[2024-11-11 12:15:12,771] INFO main.py:113 Syncing feature wasm-main-webtransport with previous active wasm-main-videodec
[2024-11-11 12:15:12,771] DEBUG main.py:118 Creating local branch origin/wasm-main-webtransport
[2024-11-11 12:15:12,901] DEBUG main.py:63 Rebasing wasm-main-webtransport onto wasm-main-videodec until origin/wasm-main-videodec
[2024-11-11 12:15:12,901] DEBUG main.py:68 Backing up wasm-main-webtransport into wasm-main-webtransport-2024-11-11
[2024-11-11 12:15:13,263] INFO main.py:113 Syncing feature wasm-main-wip with previous active wasm-main-webtransport
[2024-11-11 12:15:13,264] DEBUG main.py:118 Creating local branch origin/wasm-main-wip
[2024-11-11 12:15:13,373] DEBUG main.py:63 Rebasing wasm-main-wip onto wasm-main-webtransport until origin/wasm-main-webtransport
[2024-11-11 12:15:13,373] DEBUG main.py:68 Backing up wasm-main-wip into wasm-main-wip-2024-11-11
[2024-11-11 12:15:13,990] INFO main.py:183 Making target branch gst.wasm based on origin/wasm-main-wip
[2024-11-11 12:15:14,121] DEBUG main.py:189 Backing up target branch into gst.wasm-2024-11-11
[2024-11-11 12:15:14,293] DEBUG main.py:78 Pushing meson_fix_nls-2024-11-11 to origin
[2024-11-11 12:15:16,371] DEBUG main.py:78 Pushing meson_fix_nls to origin
[2024-11-11 12:15:18,024] DEBUG main.py:78 Pushing wasm-main-function-pointer-2024-11-11 to origin
[2024-11-11 12:15:19,960] DEBUG main.py:78 Pushing wasm-main-function-pointer to origin
[2024-11-11 12:15:21,667] DEBUG main.py:78 Pushing wasm-main-enable-2024-11-11 to origin
[2024-11-11 12:15:23,540] DEBUG main.py:78 Pushing wasm-main-enable to origin
[2024-11-11 12:15:25,649] DEBUG main.py:78 Pushing wasm-main-test-2024-11-11 to origin
[2024-11-11 12:15:28,994] DEBUG main.py:78 Pushing wasm-main-test to origin
[2024-11-11 12:15:31,943] DEBUG main.py:78 Pushing wasm-main-openal-2024-11-11 to origin
[2024-11-11 12:15:33,990] DEBUG main.py:78 Pushing wasm-main-openal to origin
[2024-11-11 12:15:36,244] DEBUG main.py:78 Pushing wasm-main-gl-support-2024-11-11 to origin
[2024-11-11 12:15:38,291] DEBUG main.py:78 Pushing wasm-main-gl-support to origin
[2024-11-11 12:15:41,300] DEBUG main.py:78 Pushing wasm-main-videodec-2024-11-11 to origin
[2024-11-11 12:15:43,310] DEBUG main.py:78 Pushing wasm-main-videodec to origin
[2024-11-11 12:15:45,415] DEBUG main.py:78 Pushing wasm-main-webtransport-2024-11-11 to origin
[2024-11-11 12:15:47,372] DEBUG main.py:78 Pushing wasm-main-webtransport to origin
[2024-11-11 12:15:49,658] DEBUG main.py:78 Pushing wasm-main-wip-2024-11-11 to origin
[2024-11-11 12:15:51,598] DEBUG main.py:78 Pushing wasm-main-wip to origin
[2024-11-11 12:15:53,961] DEBUG main.py:78 Pushing gst.wasm-2024-11-11 to origin
[2024-11-11 12:15:55,812] DEBUG main.py:78 Pushing gst.wasm to origin
forccon@forccon-fluendo:~/checkout/fluendo/git-upstream-workflow$ 
```

**Pull request merged**
